---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "fastqsamtools"
description: Converts a SAM/BAM/CRAM file to FASTQ
keywords:
  - bam
  - sam
  - cram
  - fastq
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
        These files are generated as output by short read aligners like BWA.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
      identifier: biotools:samtools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies: []
  - interleave:
      type: boolean
      description: Set true for interleaved fastq file
output:
  fastq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_{1,2}.fastq.gz":
          type: file
          description: Compressed FASTQ file(s) with reads with either the READ1 or
            READ2 flag set in separate files.
          pattern: "*_{1,2}.fastq.gz"
          ontologies: []
  other:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_other.fastq.gz":
          type: file
          description: Compressed FASTQ file with reads with either both READ1 and READ2
            flags set or unset
          pattern: "*_other.fastq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAM

authors:
  - "@sylvia"
maintainers:
  - "@sylvia"
